import 'package:flutter/material.dart';
import '../models/donut.dart';
import '../widgets/donut_tile.dart';
import 'details_page.dart';
import 'all_products_page.dart';
import 'favorites_page.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int selectedCategoryIndex = 0;
  bool showAll = false;
  bool isGrid = true;

  final List<String> categoriesIcons = [
    'lib/icons/Donuts.png',
    'lib/icons/Juices.png',
    'lib/icons/malteada.png',
    'lib/icons/burguer.png',
    'lib/icons/pizza.png',
    'lib/icons/un-pan.png',
    'lib/icons/TresDonas.png',
  ];

  // Category keys aligned 1:1 with categoriesIcons
  final List<String> categoryKeys = [
    'Dunkins',
    'Juices',
    'Frapes',
    'Burgers',
    'Pizzas',
    'Panes',
    'Paquetes',
  ];

  // Display names for each product category
  final List<String> categoryNames = [
    'Donuts',
    'Drinks',
    'Frappes',
    'Burgers',
    'Pizzas',
    'Breads',
    'Packs',
  ];


  // Main product list containing all items (Donuts, Juices, Frappes, etc.)
  final List<Donut> donuts = [
    Donut(
      name: "Color Sprinkles",
      imagePath: 'lib/images/donut/ChsiapasColor.png',
      price: 36,
      description: "Glazed donut with vibrant color sprinkles to brighten any moment of the day.",
      category: "Dunkins",
      backgroundColor: 0xFFE8F3FF,
      accentColor: 0xFFB3DBFF,
      heroTag: 'donut-chispas-color',
      ingredients: ["Wheat flour", "Sugar", "Eggs", "Butter", "Milk", "Yeast", "Color sprinkles", "Vanilla glaze"],
      preparationMethod: "Mix dry ingredients, add liquids and knead until smooth. Let rest 1 hour, shape donuts and fry in hot oil. Decorate with glaze and sprinkles.",
      nutritionalInfo: {
        "Calories": "280 kcal",
        "Fat": "12g",
        "Carbs": "38g",
        "Protein": "4g",
        "Sugars": "18g"
      },
      preparationTime: 25,
      origin: "Traditional American recipe",
      allergens: ["Gluten", "Eggs", "Dairy"],
      servingSize: "1 piece (85g)",
    ),
    Donut(
      name: "Googly Eyes",
      imagePath: 'lib/images/donut/ConOjos.png',
      price: 45,
      description: "Fun donut with sweet eyes that will make kids and adults smile.",
      category: "Dunkins",
      backgroundColor: 0xFFFFE8EF,
      accentColor: 0xFFFFC7D7,
      heroTag: 'donut-con-ojos',
      ingredients: ["Wheat flour", "Sugar", "Eggs", "Butter", "Milk", "Yeast", "Pink glaze", "Sugar eyes", "Food coloring"],
      preparationMethod: "Prepare the base dough, let it rise, fry the donuts and decorate with pink glaze. Add sugar eyes while the glaze is fresh.",
      nutritionalInfo: {
        "Calories": "320 kcal",
        "Fat": "15g",
        "Carbs": "42g",
        "Protein": "5g",
        "Sugars": "22g"
      },
      preparationTime: 30,
      origin: "Special house creation",
      allergens: ["Gluten", "Eggs", "Dairy", "Artificial coloring"],
      servingSize: "1 piece (90g)",
    ),
    Donut(
      name: "Choco Chips",
      imagePath: 'lib/images/donut/ChispasChocolate.png',
      price: 48,
      description: "Chocolate donut with semi-sweet chocolate chips for cocoa lovers.",
      category: "Dunkins",
      backgroundColor: 0xFFF3E9FF,
      accentColor: 0xFFD9C6FF,
      heroTag: 'donut-chispas-choco',
      ingredients: ["Wheat flour", "Cocoa powder", "Sugar", "Eggs", "Butter", "Milk", "Yeast", "Chocolate chips", "Chocolate glaze"],
      preparationMethod: "Mix flour with cocoa, add liquids and chocolate chips. Knead, let rise, shape donuts and fry. Cover with chocolate glaze.",
      nutritionalInfo: {
        "Calories": "350 kcal",
        "Fat": "18g",
        "Carbs": "45g",
        "Protein": "6g",
        "Sugars": "25g"
      },
      preparationTime: 35,
      origin: "Inspired by Belgian tradition",
      allergens: ["Gluten", "Eggs", "Dairy", "Cocoa"],
      servingSize: "1 piece (95g)",
    ),
    Donut(
      name: "Belgian Chocolate",
      imagePath: 'lib/images/donut/DeChocolate.png',
      price: 40,
      description: "Classic donut covered with high-quality Belgian chocolate.",
      category: "Dunkins",
      backgroundColor: 0xFFF2ECE6,
      accentColor: 0xFFE1D6CC,
      heroTag: 'donut-chocolate',
      ingredients: ["Wheat flour", "Belgian cocoa", "Sugar", "Eggs", "Butter", "Milk", "Yeast", "Chocolate coating"],
      preparationMethod: "Prepare base dough, let rise, fry donuts and dip in melted chocolate. Let cool for chocolate to set.",
      nutritionalInfo: {
        "Calories": "310 kcal",
        "Fat": "16g",
        "Carbs": "40g",
        "Protein": "5g",
        "Sugars": "20g"
      },
      preparationTime: 30,
      origin: "Belgian tradition",
      allergens: ["Gluten", "Eggs", "Dairy", "Cocoa"],
      servingSize: "1 piece (88g)",
    ),
    // Donas extra
    Donut(
      name: "Pink Glazed",
      imagePath: 'lib/images/donut/glass_rosa.png',
      price: 38,
      description: "Pink glazed donut with strawberry flavor, perfect for special occasions.",
      category: "Dunkins",
      backgroundColor: 0xFFFFEEF4,
      accentColor: 0xFFFFD6E7,
      heroTag: 'donut-rosa',
      ingredients: ["Wheat flour", "Sugar", "Eggs", "Butter", "Milk", "Yeast", "Strawberry extract", "Pink coloring", "Strawberry glaze"],
      preparationMethod: "Prepare base dough, add strawberry extract, let rise and fry. Decorate with pink strawberry glaze while hot.",
      nutritionalInfo: {
        "Calories": "290 kcal",
        "Fat": "13g",
        "Carbs": "39g",
        "Protein": "4g",
        "Sugars": "19g"
      },
      preparationTime: 28,
      origin: "Inspired by French pastry",
      allergens: ["Gluten", "Eggs", "Dairy", "Artificial coloring"],
      servingSize: "1 piece (87g)",
    ),
    Donut(
      name: "Condensed Milk",
      imagePath: 'lib/images/donut/lechera.png',
      price: 44,
      description: "Donut filled with condensed milk, creamy and sweet like a traditional dessert.",
      category: "Dunkins",
      backgroundColor: 0xFFF7FFF2,
      accentColor: 0xFFDBFFCA,
      heroTag: 'donut-lechera',
      ingredients: ["Wheat flour", "Sugar", "Eggs", "Butter", "Milk", "Yeast", "Condensed milk", "Powdered sugar", "Vanilla"],
      preparationMethod: "Prepare base dough, let rise and fry. Fill with condensed milk using a piping bag. Sprinkle with powdered sugar.",
      nutritionalInfo: {
        "Calories": "380 kcal",
        "Fat": "20g",
        "Carbs": "48g",
        "Protein": "7g",
        "Sugars": "28g"
      },
      preparationTime: 40,
      origin: "Mexican tradition",
      allergens: ["Gluten", "Eggs", "Dairy"],
      servingSize: "1 piece (100g)",
    ),
    Donut(
      name: "Chocolate Chip Ring",
      imagePath: 'lib/images/donut/rosquilla_chispas.png',
      price: 42,
      description: "Traditional ring donut with chocolate chips, crunchy outside and soft inside.",
      category: "Dunkins",
      backgroundColor: 0xFFE8F3FF,
      accentColor: 0xFFB3DBFF,
      heroTag: 'donut-rosquilla-chispas',
      ingredients: ["Wheat flour", "Sugar", "Eggs", "Butter", "Milk", "Yeast", "Chocolate chips", "Cinnamon", "Nutmeg"],
      preparationMethod: "Mix dry ingredients with chips, add liquids and knead. Shape rings, let rise and fry in hot oil until golden.",
      nutritionalInfo: {
        "Calories": "320 kcal",
        "Fat": "14g",
        "Carbs": "44g",
        "Protein": "5g",
        "Sugars": "21g"
      },
      preparationTime: 35,
      origin: "Spanish tradition",
      allergens: ["Gluten", "Eggs", "Dairy", "Cocoa"],
      servingSize: "1 piece (92g)",
    ),
    Donut(
      name: "Chocolate Ring",
      imagePath: 'lib/images/donut/rosquilla_chocolate.png',
      price: 43,
      description: "Chocolate ring donut with intense cocoa flavor, perfect for breakfast.",
      category: "Dunkins",
      backgroundColor: 0xFFF2ECE6,
      accentColor: 0xFFE1D6CC,
      heroTag: 'donut-rosquilla-choco',
      ingredients: ["Wheat flour", "Cocoa powder", "Sugar", "Eggs", "Butter", "Milk", "Yeast", "Dark chocolate", "Vanilla"],
      preparationMethod: "Mix flour with cocoa, add liquids and knead. Shape rings, let rise and fry until golden brown.",
      nutritionalInfo: {
        "Calories": "340 kcal",
        "Fat": "16g",
        "Carbs": "46g",
        "Protein": "6g",
        "Sugars": "23g"
      },
      preparationTime: 32,
      origin: "Spanish tradition with a modern twist",
      allergens: ["Gluten", "Eggs", "Dairy", "Cocoa"],
      servingSize: "1 piece (94g)",
    ),

    // Paquetes de donuts destacados
    Donut(
      name: "4 Donuts Pack",
      imagePath: 'lib/images/paquete_donuts/4rosquillas.png',
      price: 120,
      description: "Assorted box of 4 donuts with a variety of flavors to share.",
      category: "Paquetes",
      backgroundColor: 0xFFFFF4E5,
      accentColor: 0xFFFFE0B2,
      heroTag: 'pack-4',
      ingredients: ["4 assorted donuts", "Decorative box", "Variety of glazes"],
      preparationMethod: "Select 4 fresh donuts, place in decorative box, and seal.",
      nutritionalInfo: {"Calories": "1200 kcal", "Fat": "60g", "Carbs": "160g", "Protein": "20g"},
      preparationTime: 5,
      origin: "Special house selection",
      allergens: ["Gluten", "Eggs", "Dairy"],
      servingSize: "4 donuts (340g)",
    ),
    Donut(
      name: "Donut Mix",
      imagePath: 'lib/images/paquete_donuts/rosquillas_multisabor.png',
      price: 150,
      description: "Special selection of donuts with assorted flavors.",
      category: "Paquetes",
      backgroundColor: 0xFFE8FFF3,
      accentColor: 0xFFB2FFD9,
      heroTag: 'pack-mix',
      ingredients: ["Assorted donuts", "Different glazes", "Decorations"],
      preparationMethod: "Prepare donuts with different flavors, decorate, and pack.",
      nutritionalInfo: {"Calories": "900 kcal", "Fat": "45g", "Carbs": "120g", "Protein": "15g"},
      preparationTime: 8,
      origin: "Special house selection",
      allergens: ["Gluten", "Eggs", "Dairy"],
      servingSize: "6 donuts (300g)",
    ),
    Donut(
      name: "Donut Duo",
      imagePath: 'lib/images/paquete_donuts/2donas.png',
      price: 70,
      description: "Pack of 2 donuts, perfect for sharing.",
      category: "Paquetes",
      backgroundColor: 0xFFF0F7FF,
      accentColor: 0xFFD6E9FF,
      heroTag: 'pack-2',
      ingredients: ["2 fresh donuts", "Individual packaging"],
      preparationMethod: "Select 2 fresh donuts and pack.",
      nutritionalInfo: {"Calories": "600 kcal", "Fat": "30g", "Carbs": "80g", "Protein": "10g"},
      preparationTime: 3,
      origin: "Basic pack",
      allergens: ["Gluten", "Eggs", "Dairy"],
      servingSize: "2 donuts (170g)",
    ),
    Donut(
      name: "Choco & Strawberry",
      imagePath: 'lib/images/paquete_donuts/donas_chocolateyfresa.png',
      price: 135,
      description: "Perfect combination of chocolate and strawberry in a special pack.",
      category: "Paquetes",
      backgroundColor: 0xFFFFE8F0,
      accentColor: 0xFFFFC9DA,
      heroTag: 'pack-choco-fresa',
      ingredients: ["Chocolate donuts", "Strawberry donuts", "Special glazes"],
      preparationMethod: "Prepare chocolate and strawberry donuts, decorate, and pack together.",
      nutritionalInfo: {"Calories": "800 kcal", "Fat": "40g", "Carbs": "100g", "Protein": "12g"},
      preparationTime: 6,
      origin: "Special combination",
      allergens: ["Gluten", "Eggs", "Dairy", "Cocoa"],
      servingSize: "3 donuts (255g)",
    ),
    Donut(
      name: "Cream & Chips",
      imagePath: 'lib/images/paquete_donuts/donas_cremaychispas.png',
      price: 140,
      description: "Creamy donuts with chocolate chips, irresistible.",
      category: "Paquetes",
      backgroundColor: 0xFFEAF7E7,
      accentColor: 0xFFCFEBC8,
      heroTag: 'pack-cremas',
      ingredients: ["Creamy donuts", "Chocolate chips", "Whipped cream"],
      preparationMethod: "Prepare donuts with creamy filling, decorate with chips, and pack.",
      nutritionalInfo: {"Calories": "850 kcal", "Fat": "42g", "Carbs": "110g", "Protein": "14g"},
      preparationTime: 7,
      origin: "Creamy specialty",
      allergens: ["Gluten", "Eggs", "Dairy", "Cocoa"],
      servingSize: "3 donuts (240g)",
    ),
    Donut(
      name: "Glassy Choco",
      imagePath: 'lib/images/paquete_donuts/donas_glassychocolate.png',
      price: 145,
      description: "Glazed donuts with high-quality Belgian chocolate.",
      category: "Paquetes",
      backgroundColor: 0xFFFFF7E5,
      accentColor: 0xFFFFE5B0,
      heroTag: 'pack-glassy',
      ingredients: ["Base donuts", "Belgian chocolate", "Special glaze"],
      preparationMethod: "Prepare donuts, cover with melted Belgian chocolate, and let cool.",
      nutritionalInfo: {"Calories": "900 kcal", "Fat": "45g", "Carbs": "115g", "Protein": "15g"},
      preparationTime: 8,
      origin: "Belgian tradition",
      allergens: ["Gluten", "Eggs", "Dairy", "Cocoa"],
      servingSize: "3 donuts (255g)",
    ),
    Donut(
      name: "Simple Ring",
      imagePath: 'lib/images/paquete_donuts/rosquilla.png',
      price: 60,
      description: "Classic traditional ring, simple and delicious.",
      category: "Paquetes",
      backgroundColor: 0xFFF6FAFF,
      accentColor: 0xFFDDECFF,
      heroTag: 'pack-simple',
      ingredients: ["Traditional ring", "Powdered sugar"],
      preparationMethod: "Prepare traditional ring, sprinkle with powdered sugar.",
      nutritionalInfo: {"Calories": "300 kcal", "Fat": "15g", "Carbs": "40g", "Protein": "5g"},
      preparationTime: 4,
      origin: "Spanish tradition",
      allergens: ["Gluten", "Eggs", "Dairy"],
      servingSize: "2 rings (120g)",
    ),
    // Bebidas (juices)
    Donut(
      name: "Lemonade",
      imagePath: 'lib/images/juices/limonada.png',
      price: 30,
      description: "Refreshing natural lemonade with fresh lemons, perfect for summer.",
      category: "Juices",
      backgroundColor: 0xFFE7FFF3,
      accentColor: 0xFFBFFFE0,
      heroTag: 'juice-limonada',
      ingredients: ["Fresh lemons", "Water", "Sugar", "Ice", "Mint", "Agave syrup"],
      preparationMethod: "Squeeze fresh lemons, mix with water, sugar, and agave syrup. Add ice and garnish with mint.",
      nutritionalInfo: {
        "Calories": "80 kcal",
        "Fat": "0g",
        "Carbs": "22g",
        "Protein": "0g",
        "Vitamin C": "45mg"
      },
      preparationTime: 3,
      origin: "Mediterranean tradition",
      allergens: [],
      servingSize: "1 glass (300ml)",
    ),
    Donut(
      name: "Orange Juice",
      imagePath: 'lib/images/juices/naranja.png',
      price: 32,
      description: "Freshly squeezed orange juice, rich in vitamin C.",
      category: "Juices",
      backgroundColor: 0xFFFFF7E5,
      accentColor: 0xFFFFE5B0,
      heroTag: 'juice-naranja',
      ingredients: ["Fresh oranges", "Water", "Sugar", "Ice"],
      preparationMethod: "Squeeze fresh oranges, strain and mix with water and sugar.",
      nutritionalInfo: {"Calories": "120 kcal", "Fat": "0g", "Carbs": "30g", "Protein": "2g", "Vitamin C": "70mg"},
      preparationTime: 4,
      origin: "Mediterranean recipe",
      allergens: [],
      servingSize: "1 glass (300ml)",
    ),
    Donut(
      name: "Hibiscus Water",
      imagePath: 'lib/images/juices/jamaica.png',
      price: 28,
      description: "Refreshing hibiscus flower water, natural and delicious.",
      category: "Juices",
      backgroundColor: 0xFFFFE8F0,
      accentColor: 0xFFFFC9DA,
      heroTag: 'juice-jamaica',
      ingredients: ["Hibiscus flowers", "Water", "Sugar", "Ice"],
      preparationMethod: "Boil hibiscus flowers, strain and mix with water and sugar.",
      nutritionalInfo: {"Calories": "80 kcal", "Fat": "0g", "Carbs": "20g", "Protein": "0g"},
      preparationTime: 5,
      origin: "Mexican tradition",
      allergens: [],
      servingSize: "1 glass (300ml)",
    ),
    Donut(
      name: "Iced Matcha",
      imagePath: 'lib/images/juices/matcha.png',
      price: 38,
      description: "Cold drink made with premium matcha tea, energizing and healthy.",
      category: "Juices",
      backgroundColor: 0xFFEAF7E7,
      accentColor: 0xFFCFEBC8,
      heroTag: 'juice-matcha',
      ingredients: ["Premium matcha tea", "Milk", "Sugar", "Ice"],
      preparationMethod: "Prepare matcha tea, mix with milk and sugar, add ice.",
      nutritionalInfo: {"Calories": "90 kcal", "Fat": "2g", "Carbs": "18g", "Protein": "3g", "Antioxidants": "High"},
      preparationTime: 6,
      origin: "Japanese tradition",
      allergens: ["Dairy"],
      servingSize: "1 glass (300ml)",
    ),
    Donut(
      name: "Iced Mate",
      imagePath: 'lib/images/juices/mate.png',
      price: 34,
      description: "Cold yerba mate infusion, energizing and refreshing.",
      category: "Juices",
      backgroundColor: 0xFFE8FFF6,
      accentColor: 0xFFBDFBE3,
      heroTag: 'juice-mate',
      ingredients: ["Yerba mate", "Water", "Sugar", "Ice", "Lemon"],
      preparationMethod: "Prepare mate infusion, chill and mix with sugar and lemon.",
      nutritionalInfo: {"Calories": "70 kcal", "Fat": "0g", "Carbs": "18g", "Protein": "1g"},
      preparationTime: 4,
      origin: "Argentinian tradition",
      allergens: [],
      servingSize: "1 glass (300ml)",
    ),
    Donut(
      name: "Bottled Water",
      imagePath: 'lib/images/juices/botella_de_agua.png',
      price: 18,
      description: "Purified water 600ml, fresh and crystal clear.",
      category: "Juices",
      backgroundColor: 0xFFF0F7FF,
      accentColor: 0xFFD6E9FF,
      heroTag: 'juice-botella',
      ingredients: ["Purified water"],
      preparationMethod: "Filter and purify water, bottle it.",
      nutritionalInfo: {"Calories": "0 kcal", "Fat": "0g", "Carbs": "0g", "Protein": "0g"},
      preparationTime: 1,
      origin: "Purified water",
      allergens: [],
      servingSize: "1 bottle (600ml)",
    ),
    Donut(
      name: "Glass of Water",
      imagePath: 'lib/images/juices/vaso_de_agua.png',
      price: 12,
      description: "Glass of cold water, refreshing and healthy.",
      category: "Juices",
      backgroundColor: 0xFFF5FBFF,
      accentColor: 0xFFE0F3FF,
      heroTag: 'juice-vaso',
      ingredients: ["Purified water", "Ice"],
      preparationMethod: "Serve purified water with ice in a glass.",
      nutritionalInfo: {"Calories": "0 kcal", "Fat": "0g", "Carbs": "0g", "Protein": "0g"},
      preparationTime: 1,
      origin: "Purified water",
      allergens: [],
      servingSize: "1 glass (250ml)",
    ),
    // Frapés
    Donut(
      name: "Coffee Frappe",
      imagePath: 'lib/images/frapes/cafe.png',
      price: 55,
      description: "Arabica coffee frappe with ice, creamy and refreshing for any time of day.",
      category: "Frapes",
      backgroundColor: 0xFFEFE7E2,
      accentColor: 0xFFDCCFC7,
      heroTag: 'frape-cafe',
      ingredients: ["Arabica coffee", "Milk", "Ice", "Sugar", "Whipped cream", "Vanilla syrup", "Cinnamon"],
      preparationMethod: "Prepare espresso, blend with milk, sugar, and ice. Serve with whipped cream and sprinkle cinnamon.",
      nutritionalInfo: {
        "Calories": "180 kcal",
        "Fat": "8g",
        "Carbs": "22g",
        "Protein": "6g",
        "Caffeine": "95mg"
      },
      preparationTime: 5,
      origin: "Inspired by Greek iced coffee",
      allergens: ["Dairy"],
      servingSize: "1 glass (350ml)",
    ),
    Donut(
      name: "Chocolate Frappe",
      imagePath: 'lib/images/frapes/chocolate.png',
      price: 58,
      description: "Creamy Belgian chocolate frappe with ice, perfect for cocoa lovers.",
      category: "Frapes",
      backgroundColor: 0xFFEFE8F3,
      accentColor: 0xFFD9CFE6,
      heroTag: 'frape-chocolate',
      ingredients: ["Belgian chocolate", "Milk", "Ice", "Sugar", "Whipped cream", "Cocoa powder", "Vanilla"],
      preparationMethod: "Melt Belgian chocolate, blend with milk, sugar, and ice. Serve with whipped cream and sprinkle cocoa.",
      nutritionalInfo: {
        "Calories": "220 kcal",
        "Fat": "12g",
        "Carbs": "28g",
        "Protein": "7g",
        "Sugars": "24g"
      },
      preparationTime: 6,
      origin: "Inspired by Belgian tradition",
      allergens: ["Dairy", "Cocoa"],
      servingSize: "1 glass (350ml)",
    ),
    Donut(
      name: "Strawberry Frappe",
      imagePath: 'lib/images/frapes/fresa.png',
      price: 56,
      description: "Fresh and sweet strawberry frappe, perfect for summer.",
      category: "Frapes",
      backgroundColor: 0xFFFFEDF3,
      accentColor: 0xFFFFD5E3,
      heroTag: 'frape-fresa',
      ingredients: ["Fresh strawberries", "Milk", "Ice", "Sugar", "Whipped cream"],
      preparationMethod: "Blend strawberries with milk, sugar, and ice. Serve with whipped cream.",
      nutritionalInfo: {"Calories": "190 kcal", "Fat": "8g", "Carbs": "28g", "Protein": "5g"},
      preparationTime: 5,
      origin: "Inspired by tropical smoothies",
      allergens: ["Dairy"],
      servingSize: "1 glass (350ml)",
    ),
    Donut(
      name: "Orange Frappe",
      imagePath: 'lib/images/frapes/naranja.png',
      price: 54,
      description: "Citrus orange frappe, refreshing and energizing.",
      category: "Frapes",
      backgroundColor: 0xFFFFF3E7,
      accentColor: 0xFFFFE0BE,
      heroTag: 'frape-naranja',
      ingredients: ["Orange juice", "Milk", "Ice", "Sugar", "Whipped cream"],
      preparationMethod: "Blend orange juice with milk, sugar, and ice.",
      nutritionalInfo: {"Calories": "180 kcal", "Fat": "7g", "Carbs": "30g", "Protein": "4g"},
      preparationTime: 5,
      origin: "Inspired by citrus drinks",
      allergens: ["Dairy"],
      servingSize: "1 glass (350ml)",
    ),
    Donut(
      name: "Chamoy Milkshake",
      imagePath: 'lib/images/frapes/malteada_chamoy.png',
      price: 62,
      description: "Milkshake with chamoy, a unique sweet and sour flavor.",
      category: "Frapes",
      backgroundColor: 0xFFFFF0EE,
      accentColor: 0xFFFFD2CC,
      heroTag: 'frape-chamoy',
      ingredients: ["Milk", "Chamoy", "Ice", "Sugar", "Whipped cream"],
      preparationMethod: "Blend milk with chamoy, sugar, and ice.",
      nutritionalInfo: {"Calories": "220 kcal", "Fat": "10g", "Carbs": "32g", "Protein": "6g"},
      preparationTime: 6,
      origin: "Mexican tradition",
      allergens: ["Dairy"],
      servingSize: "1 glass (350ml)",
    ),
    Donut(
      name: "Chocolate Chip Milkshake",
      imagePath: 'lib/images/frapes/malteada_chispas.png',
      price: 64,
      description: "Creamy milkshake with chocolate chips, irresistible.",
      category: "Frapes",
      backgroundColor: 0xFFFFEEF4,
      accentColor: 0xFFFFD6E7,
      heroTag: 'frape-chispas',
      ingredients: ["Milk", "Chocolate chips", "Ice", "Sugar", "Whipped cream"],
      preparationMethod: "Blend milk with chips, sugar, and ice.",
      nutritionalInfo: {"Calories": "240 kcal", "Fat": "12g", "Carbs": "35g", "Protein": "7g"},
      preparationTime: 6,
      origin: "Inspired by classic milkshakes",
      allergens: ["Dairy", "Cocoa"],
      servingSize: "1 glass (350ml)",
    ),
    Donut(
      name: "Berry Milkshake",
      imagePath: 'lib/images/frapes/malteada_morada.png',
      price: 63,
      description: "Milkshake with purple berries, antioxidant and delicious.",
      category: "Frapes",
      backgroundColor: 0xFFF3E9FF,
      accentColor: 0xFFD9C6FF,
      heroTag: 'frape-morada',
      ingredients: ["Purple berries", "Milk", "Ice", "Sugar", "Whipped cream"],
      preparationMethod: "Blend purple berries with milk, sugar, and ice.",
      nutritionalInfo: {"Calories": "200 kcal", "Fat": "8g", "Carbs": "32g", "Protein": "5g"},
      preparationTime: 6,
      origin: "Inspired by forest berries",
      allergens: ["Dairy"],
      servingSize: "1 glass (350ml)",
    ),
    Donut(
      name: "Smoothie",
      imagePath: 'lib/images/frapes/licuado.png',
      price: 40,
      description: "Creamy and nutritious smoothie, perfect for any time.",
      category: "Frapes",
      backgroundColor: 0xFFF0F7FF,
      accentColor: 0xFFD6E9FF,
      heroTag: 'frape-licuado',
      ingredients: ["Fresh fruit", "Milk", "Ice", "Sugar", "Cream"],
      preparationMethod: "Blend fresh fruit with milk, sugar, and ice until creamy.",
      nutritionalInfo: {"Calories": "180 kcal", "Fat": "6g", "Carbs": "30g", "Protein": "6g"},
      preparationTime: 5,
      origin: "Traditional recipe",
      allergens: ["Dairy"],
      servingSize: "1 glass (350ml)",
    ),
    // Pizzas (nombres según archivo)
    Donut(
      name: "Mushroom",
      imagePath: 'lib/images/pizzas/pizza_con_champinon.png',
      price: 89,
      description: "Artisan pizza with fresh mushrooms, mozzarella, and homemade tomato sauce.",
      category: "Pizzas",
      backgroundColor: 0xFFFFF5E8,
      accentColor: 0xFFFFE2B8,
      heroTag: 'pizza-champi',
      ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Fresh mushrooms", "Oregano", "Garlic", "Olive oil", "Salt", "Pepper"],
      preparationMethod: "Roll out the dough, add tomato sauce, mozzarella, and mushrooms. Bake at 250°C for 12-15 minutes until golden.",
      nutritionalInfo: {
        "Calories": "280 kcal",
        "Fat": "12g",
        "Carbs": "32g",
        "Protein": "14g",
        "Sodium": "680mg"
      },
      preparationTime: 20,
      origin: "Traditional Italian style",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 slice (150g)",
    ),
    Donut(
      name: "Pepperoni",
      imagePath: 'lib/images/pizzas/pizza_de_peperoni.png',
      price: 99,
      description: "Classic pizza with Italian pepperoni, mozzarella, and tomato sauce, everyone's favorite.",
      category: "Pizzas",
      backgroundColor: 0xFFFFF0EE,
      accentColor: 0xFFFFD2CC,
      heroTag: 'pizza-pepperoni',
      ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Italian pepperoni", "Oregano", "Garlic", "Olive oil", "Red bell pepper"],
      preparationMethod: "Roll out the dough, add tomato sauce, mozzarella, and pepperoni. Bake at 250°C for 12-15 minutes until cheese is bubbly.",
      nutritionalInfo: {
        "Calories": "320 kcal",
        "Fat": "16g",
        "Carbs": "30g",
        "Protein": "16g",
        "Sodium": "850mg"
      },
      preparationTime: 18,
      origin: "American-Italian style",
      allergens: ["Gluten", "Dairy", "Pork"],
      servingSize: "1 slice (160g)",
    ),
    Donut(
      name: "Cheese",
      imagePath: 'lib/images/pizzas/pizza_de_queso.png',
      price: 95,
      description: "Classic mozzarella cheese pizza, simple and delicious.",
      category: "Pizzas",
      backgroundColor: 0xFFEFF8FF,
      accentColor: 0xFFD8EDFF,
      heroTag: 'pizza-queso',
      ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Oregano", "Olive oil"],
      preparationMethod: "Roll out the dough, add tomato sauce and mozzarella. Bake at 250°C for 12-15 minutes.",
      nutritionalInfo: {"Calories": "280 kcal", "Fat": "12g", "Carbs": "32g", "Protein": "14g"},
      preparationTime: 18,
      origin: "Classic Italian tradition",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 slice (150g)",
    ),
    Donut(
      name: "Pan Pizza",
      imagePath: 'lib/images/pizzas/pizza_de_sarten.png',
      price: 92,
      description: "Pan-style pizza, crispy and golden on the outside.",
      category: "Pizzas",
      backgroundColor: 0xFFEFFFEF,
      accentColor: 0xFFDAFFD9,
      heroTag: 'pizza-sarten',
      ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Fresh ingredients"],
      preparationMethod: "Cook in a hot pan, add ingredients, and cook until the base is crispy.",
      nutritionalInfo: {"Calories": "290 kcal", "Fat": "13g", "Carbs": "33g", "Protein": "13g"},
      preparationTime: 20,
      origin: "Modern Italian style",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 slice (155g)",
    ),
    Donut(
      name: "Geometric",
      imagePath: 'lib/images/pizzas/pizza_geometrica.png',
      price: 104,
      description: "Pizza with a unique geometric design, culinary art.",
      category: "Pizzas",
      backgroundColor: 0xFFF3EFFD,
      accentColor: 0xFFE0D8FF,
      heroTag: 'pizza-geo',
      ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Decorative ingredients"],
      preparationMethod: "Create a geometric design with ingredients, bake at 250°C for 15 minutes.",
      nutritionalInfo: {"Calories": "320 kcal", "Fat": "15g", "Carbs": "35g", "Protein": "15g"},
      preparationTime: 25,
      origin: "Modern culinary art",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 slice (160g)",
    ),
    Donut(
      name: "Vegetarian",
      imagePath: 'lib/images/pizzas/pizza_vegetariana.png',
      price: 97,
      description: "Pizza with fresh vegetables, healthy and delicious.",
      category: "Pizzas",
      backgroundColor: 0xFFEFFFF7,
      accentColor: 0xFFD7FFE7,
      heroTag: 'pizza-veg',
      ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Bell peppers", "Mushrooms", "Onion", "Olives"],
      preparationMethod: "Roll out the dough, add sauce and fresh vegetables. Bake at 250°C for 15 minutes.",
      nutritionalInfo: {"Calories": "260 kcal", "Fat": "10g", "Carbs": "35g", "Protein": "12g"},
      preparationTime: 20,
      origin: "Healthy option",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 slice (150g)",
    ),
    Donut(
      name: "Italian",
      imagePath: 'lib/images/pizzas/pizza_italiana.png',
      price: 110,
      description: "Authentic Italian-style pizza with traditional ingredients.",
      category: "Pizzas",
      backgroundColor: 0xFFFFF1F7,
      accentColor: 0xFFFFD6E7,
      heroTag: 'pizza-italiana',
      ingredients: ["Italian dough", "Tomato sauce", "Buffalo mozzarella", "Basil", "Olive oil"],
      preparationMethod: "Use traditional Italian dough, add authentic ingredients, and bake in a wood-fired oven.",
      nutritionalInfo: {"Calories": "340 kcal", "Fat": "16g", "Carbs": "38g", "Protein": "16g"},
      preparationTime: 22,
      origin: "Authentic Italian tradition",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 slice (165g)",
    ),
    Donut(
      name: "Slice",
      imagePath: 'lib/images/pizzas/rebanada_de_pizza.png',
      price: 108,
      description: "Fresh pizza slice, perfect for an individual portion.",
      category: "Pizzas",
      backgroundColor: 0xFFFFF6EC,
      accentColor: 0xFFFFE1C2,
      heroTag: 'pizza-slice',
      ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Various ingredients"],
      preparationMethod: "Cut a fresh pizza slice and heat in the oven.",
      nutritionalInfo: {"Calories": "280 kcal", "Fat": "12g", "Carbs": "32g", "Protein": "14g"},
      preparationTime: 5,
      origin: "Individual portion",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 slice (120g)",
    ),

    // Burgers
    Donut(
      name: "Classic Burger",
      imagePath: 'lib/images/burgers/burguer_clasica.png',
      price: 65,
      description: "Classic burger with 100% natural beef, lettuce, tomato, onion, and special sauces.",
      category: "Burgers",
      backgroundColor: 0xFFFFF7E8,
      accentColor: 0xFFFFE2B3,
      heroTag: 'burger-classica',
      ingredients: ["Burger bun", "150g beef patty", "Lettuce", "Tomato", "Onion", "Cheddar cheese", "Special sauce", "Mayonnaise", "Mustard"],
      preparationMethod: "Grill the beef patty, toast the bun, add melted cheese, and assemble with all fresh ingredients.",
      nutritionalInfo: {
        "Calories": "520 kcal",
        "Fat": "28g",
        "Carbs": "35g",
        "Protein": "32g",
        "Sodium": "890mg"
      },
      preparationTime: 15,
      origin: "Traditional American style",
      allergens: ["Gluten", "Dairy", "Eggs"],
      servingSize: "1 burger (280g)",
    ),
    Donut(
      name: "Simple Burger",
      imagePath: 'lib/images/burgers/burguer_sencilla.png',
      price: 55,
      description: "Simple burger with the essential ingredients: beef, bun, and basic sauces.",
      category: "Burgers",
      backgroundColor: 0xFFFFEFEF,
      accentColor: 0xFFFFD1D1,
      heroTag: 'burger-sencilla',
      ingredients: ["Burger bun", "120g beef patty", "Lettuce", "Tomato", "Onion", "Ketchup", "Mustard"],
      preparationMethod: "Grill the beef patty, toast the bun, and assemble with fresh veggies and sauces.",
      nutritionalInfo: {
        "Calories": "420 kcal",
        "Fat": "22g",
        "Carbs": "32g",
        "Protein": "28g",
        "Sodium": "650mg"
      },
      preparationTime: 12,
      origin: "Classic American style",
      allergens: ["Gluten", "Eggs"],
      servingSize: "1 burger (220g)",
    ),
    Donut(
      name: "Toasted Burger",
      imagePath: 'lib/images/burgers/burguer_tostada.png',
      price: 62,
      description: "Burger with toasted bun, crunchy and delicious.",
      category: "Burgers",
      backgroundColor: 0xFFF5FBFF,
      accentColor: 0xFFE0F3FF,
      heroTag: 'burger-tostada',
      ingredients: ["Toasted bun", "Beef patty", "Lettuce", "Tomato", "Onion", "Cheese", "Sauces"],
      preparationMethod: "Toast the bun, cook the beef patty, and assemble with fresh ingredients.",
      nutritionalInfo: {"Calories": "480 kcal", "Fat": "24g", "Carbs": "38g", "Protein": "28g"},
      preparationTime: 15,
      origin: "American style",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 burger (230g)",
    ),
    Donut(
      name: "Double Chicken Burger",
      imagePath: 'lib/images/burgers/doble_pollo.png',
      price: 78,
      description: "Burger with double chicken breast, juicy and satisfying.",
      category: "Burgers",
      backgroundColor: 0xFFE8FFF6,
      accentColor: 0xFFBDFBE3,
      heroTag: 'burger-doble-pollo',
      ingredients: ["Burger bun", "2 chicken breasts", "Lettuce", "Tomato", "Onion", "Cheese", "Sauces"],
      preparationMethod: "Cook two chicken breasts, toast the bun, and assemble with ingredients.",
      nutritionalInfo: {"Calories": "520 kcal", "Fat": "22g", "Carbs": "35g", "Protein": "42g"},
      preparationTime: 18,
      origin: "Premium chicken option",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 burger (280g)",
    ),
    Donut(
      name: "Double Patty Burger",
      imagePath: 'lib/images/burgers/dos_pisos.png',
      price: 85,
      description: "Two-story burger with double beef patties, for the hungriest.",
      category: "Burgers",
      backgroundColor: 0xFFF0F7FF,
      accentColor: 0xFFD6E9FF,
      heroTag: 'burger-dos-pisos',
      ingredients: ["Burger bun", "2 beef patties", "Lettuce", "Tomato", "Onion", "Double cheese", "Sauces"],
      preparationMethod: "Cook two beef patties, toast the bun, and assemble in two layers with ingredients.",
      nutritionalInfo: {"Calories": "680 kcal", "Fat": "35g", "Carbs": "40g", "Protein": "48g"},
      preparationTime: 20,
      origin: "Premium American style",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 burger (320g)",
    ),
    Donut(
      name: "Extra Cheese Burger",
      imagePath: 'lib/images/burgers/mas_queso.png',
      price: 72,
      description: "Burger with extra cheese, creamy and delicious.",
      category: "Burgers",
      backgroundColor: 0xFFFFF0EE,
      accentColor: 0xFFFFD2CC,
      heroTag: 'burger-mas-queso',
      ingredients: ["Burger bun", "Beef patty", "Lettuce", "Tomato", "Onion", "Extra cheese", "Sauces"],
      preparationMethod: "Cook the beef patty, add extra melted cheese, and assemble with ingredients.",
      nutritionalInfo: {"Calories": "580 kcal", "Fat": "32g", "Carbs": "35g", "Protein": "35g"},
      preparationTime: 16,
      origin: "For cheese lovers",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 burger (260g)",
    ),
    // Panes
    Donut(
      name: "Croissant",
      imagePath: 'lib/images/panes/cuerno.png',
      price: 22,
      description: "Artisan sweet croissant, crunchy outside and soft inside.",
      category: "Panes",
      backgroundColor: 0xFFF7F3EA,
      accentColor: 0xFFE9DFC7,
      heroTag: 'pan-cuerno',
      ingredients: ["Wheat flour", "Butter", "Sugar", "Eggs", "Milk", "Yeast", "Vanilla", "Salt"],
      preparationMethod: "Prepare dough with laminated butter, shape croissants, let rise, and bake at 180°C until golden.",
      nutritionalInfo: {
        "Calories": "180 kcal",
        "Fat": "8g",
        "Carbs": "24g",
        "Protein": "4g",
        "Sugars": "6g"
      },
      preparationTime: 45,
      origin: "French tradition",
      allergens: ["Gluten", "Eggs", "Dairy"],
      servingSize: "1 piece (60g)",
    ),
    Donut(
      name: "Baguette",
      imagePath: 'lib/images/panes/barra.png',
      price: 18,
      description: "Artisan baguette, crunchy outside and soft inside.",
      category: "Panes",
      backgroundColor: 0xFFF1F1F1,
      accentColor: 0xFFDBDBDB,
      heroTag: 'pan-barra',
      ingredients: ["Wheat flour", "Yeast", "Water", "Salt", "Olive oil"],
      preparationMethod: "Knead ingredients, let rise for 2 hours, shape baguette, and bake at 200°C for 25 minutes.",
      nutritionalInfo: {"Calories": "220 kcal", "Fat": "4g", "Carbs": "42g", "Protein": "8g"},
      preparationTime: 45,
      origin: "European tradition",
      allergens: ["Gluten"],
      servingSize: "1 baguette (80g)",
    ),
    Donut(
      name: "Garlic Bread",
      imagePath: 'lib/images/panes/pan-de-ajo.png',
      price: 26,
      description: "Baked bread with garlic and butter, aromatic and delicious.",
      category: "Panes",
      backgroundColor: 0xFFFFF2E8,
      accentColor: 0xFFFFE0C6,
      heroTag: 'pan-ajo',
      ingredients: ["Base bread", "Garlic", "Butter", "Parsley", "Salt", "Pepper"],
      preparationMethod: "Mix garlic with butter, spread on bread, and bake until golden.",
      nutritionalInfo: {"Calories": "280 kcal", "Fat": "12g", "Carbs": "38g", "Protein": "6g"},
      preparationTime: 20,
      origin: "Italian tradition",
      allergens: ["Gluten", "Dairy"],
      servingSize: "1 piece (70g)",
    ),
    Donut(
      name: "Pita Bread",
      imagePath: 'lib/images/panes/pan-de-pita.png',
      price: 20,
      description: "Soft and light pita bread, perfect for wraps and sandwiches.",
      category: "Panes",
      backgroundColor: 0xFFEAF3FF,
      accentColor: 0xFFCFE1FF,
      heroTag: 'pan-pita',
      ingredients: ["Wheat flour", "Yeast", "Water", "Salt", "Olive oil"],
      preparationMethod: "Knead ingredients, let rise, shape balls, and cook in a hot pan.",
      nutritionalInfo: {"Calories": "180 kcal", "Fat": "3g", "Carbs": "35g", "Protein": "6g"},
      preparationTime: 35,
      origin: "Mediterranean tradition",
      allergens: ["Gluten"],
      servingSize: "1 piece (60g)",
    ),
    
    Donut(
      name: "Whole Wheat Loaf",
      imagePath: 'lib/images/panes/pan-de-molde (1).png',
      price: 26,
      description: "Healthy whole wheat loaf, rich in fiber and nutrients.",
      category: "Panes",
      backgroundColor: 0xFFF2FFF6,
      accentColor: 0xFFD8FFE0,
      heroTag: 'pan-molde-integral',
      ingredients: ["Whole wheat flour", "Yeast", "Water", "Salt", "Seeds", "Olive oil"],
      preparationMethod: "Mix whole wheat flour with seeds, let rise, and bake in a loaf pan.",
      nutritionalInfo: {"Calories": "200 kcal", "Fat": "5g", "Carbs": "38g", "Protein": "8g", "Fiber": "6g"},
      preparationTime: 50,
      origin: "Healthy option",
      allergens: ["Gluten"],
      servingSize: "1 slice (40g)",
    ),
  ];

  // Returns the filtered list of products for the selected category
  List<Donut> get filteredItems {
    if (showAll) return donuts;
    final key = categoryKeys[selectedCategoryIndex];
    return donuts.where((d) => d.category == key).toList();
  }

  // Main build method for the HomePage UI
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 10),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  IconButton(
                    icon: const Icon(Icons.menu_rounded, size: 28),
                    onPressed: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (_) => AllProductsPage(products: donuts),
                        ),
                      );
                    },
                  ),
                  IconButton(
                    icon: const Icon(Icons.favorite, color: Colors.pinkAccent, size: 28),
                    onPressed: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (_) => FavoritesPage(allProducts: donuts),
                        ),
                      );
                    },
                  ),
                ],
              ),
            ),
            // App Title
            Padding(
              padding: const EdgeInsets.only(left: 24.0, right: 24.0, top: 0, bottom: 8),
              child: Text(
                'Donut Shop App',
                style: TextStyle(
                  fontFamily: 'Pacifico', // Use a script-like font if available
                  fontSize: 32,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 1.5,
                  shadows: [
                    Shadow(
                      blurRadius: 6,
                      color: Color(0xFFB97A56).withOpacity(0.4),
                      offset: Offset(0, 4),
                    ),
                  ],
                  // Simulate a glazed effect with a white shadow highlight
                  foreground: Paint()
                    ..shader = LinearGradient(
                      colors: <Color>[Color(0xFF7B3F00), Color(0xFFF3E9D2), Color(0xFF7B3F00)],
                      stops: [0.0, 0.5, 1.0],
                    ).createShader(Rect.fromLTWH(0.0, 0.0, 200.0, 70.0)),
                ),
              ),
            ),
            const SizedBox(height: 8),

            // Categories
            SizedBox(
              height: 104,
              child: ListView.separated(
                padding: const EdgeInsets.symmetric(horizontal: 16.0),
                scrollDirection: Axis.horizontal,
                itemBuilder: (context, index) {
                  final iconPath = categoriesIcons[index];
                  final bool isSelected = index == selectedCategoryIndex;
                  return GestureDetector(
                    onTap: () => setState(() {
                      selectedCategoryIndex = index;
                      showAll = false;
                    }),
                    child: Column(
                      children: [
                        Container(
                          width: 54,
                          height: 54,
                          decoration: BoxDecoration(
                            color: isSelected ? const Color(0xFFFFE4EE) : const Color(0xFFF2F2F2),
                            borderRadius: BorderRadius.circular(14),
                          ),
                          child: Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Image.asset(iconPath),
                          ),
                        ),
                        const SizedBox(height: 8),
                        Text(
                          categoryNames[index],
                          style: TextStyle(
                            fontSize: 12,
                            fontWeight: isSelected ? FontWeight.w600 : FontWeight.w400,
                            color: isSelected ? Colors.black : Colors.black54,
                          ),
                        ),
                        const SizedBox(height: 6),
                        AnimatedContainer(
                          duration: const Duration(milliseconds: 200),
                          width: isSelected ? 28 : 0,
                          height: 3,
                          decoration: BoxDecoration(
                            color: Colors.pinkAccent,
                            borderRadius: BorderRadius.circular(2),
                          ),
          ),
        ],
      ),
                  );
                },
                separatorBuilder: (_, __) => const SizedBox(width: 12),
                itemCount: categoriesIcons.length,
              ),
            ),

            const SizedBox(height: 10),

            // Botón para alternar vista
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  Text('View: ', style: TextStyle(fontWeight: FontWeight.w500)),
                  IconButton(
                    icon: Icon(isGrid ? Icons.grid_view : Icons.view_list, color: Colors.pinkAccent),
                    tooltip: isGrid ? 'Switch to list' : 'Switch to grid',
                    onPressed: () => setState(() => isGrid = !isGrid),
                  ),
                ],
              ),
            ),

            // Productos
            Expanded(
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 12.0),
                child: isGrid
                    ? GridView.builder(
                        itemCount: filteredItems.length,
                        gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                          crossAxisCount: 2,
                          mainAxisSpacing: 12,
                          crossAxisSpacing: 12,
                          childAspectRatio: 0.78,
                        ),
                        itemBuilder: (context, index) {
                          final donut = filteredItems[index];
                          return DonutTile(
                            donut: donut,
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (context) => DetailsPage(donut: donut),
                                ),
                              );
                            },
                          );
                        },
                      )
                    : ListView.separated(
                        itemCount: filteredItems.length,
                        separatorBuilder: (_, __) => const SizedBox(height: 10),
                        itemBuilder: (context, index) {
                          final donut = filteredItems[index];
                          return DonutTile(
                            donut: donut,
                            onTap: () {
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (context) => DetailsPage(donut: donut),
                                ),
                              );
                            },
                            isList: true,
                          );
                        },
                      ),
              ),
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: Colors.pink,
        onPressed: () => Navigator.pushNamed(context, '/cart'),
        child: const Icon(Icons.shopping_bag_outlined),
      ),
    );
  }
}
